name: 'pr-dday-counter-action'
description: 'Make D-Day label in pull requests down by one'
author: 'Rajin9601'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  dday-labels:
    required: true
    description: 'D-Day labels as comma-seperated string in ascending order from 0'
runs:
  using: 'node12'
  main: 'dist/index.js'
